export const productData = [

    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "vegetables",
        name: "Cauliflower",
        price: 16,
        image:
            "https://c.files.bbci.co.uk/4F91/production/_108296302_cauliflowergetty.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "vegetables",
        name: "Potato",
        price: 25,
        image:
            "https://english.mathrubhumi.com/polopoly_fs/1.2329655.1577412275!/image/image.jpg_gen/derivatives/landscape_894_577/image.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "vegetables",
        name: "Tomato",
        price: 20,
        image:
            "https://post.healthline.com/wp-content/uploads/2020/09/tomatoes-1200x628-facebook-1200x628.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "vegetables",
        name: "Onion",
        price: 40,
        image: "https://cartfull.in/wp-content/uploads/2021/06/Red-Onion.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "vegetables",
        name: "LadyFinger",
        price: 25,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/61M7ZbTTlVL._SL1000_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "vegetables",
        name: "Cabbage",
        price: 20,
        image:
            "https://annaistores.com/as_content/uploads/2020/11/1587687891774.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "vegetables",
        name: "Brinjal",
        price: 15,
        image:
            "https://4.imimg.com/data4/RR/RR/GLADMIN-/wp-content-uploads-2016-04-brinjal-long-violet-500x500-400x400-500x500.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "vegetables",
        name: "Capsicum",
        price: 40,
        image:
            "https://5.imimg.com/data5/ZS/DM/SP/ANDROID-36073789/product-jpeg-500x500.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "vegetables",
        name: "Garlic",
        price: 40,
        image: "https://images-na.ssl-images-amazon.com/images/I/31eUGitRN1L.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "vegetables",
        name: "Green chilli",
        price: 10,
        image:
            "https://5.imimg.com/data5/ANDROID/Default/2020/12/AJ/RE/CU/31503960/1607436883309-jpg-500x500.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "fruits",
        name: "Apple",
        price: 120,
        image:
            "https://idsb.tmgrup.com.tr/ly/uploads/images/2020/05/13/35552.jpeg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "fruits",
        name: "Mango",
        price: 50,
        image:
            "https://static.toiimg.com/thumb/69185542.cms?width=680&height=512&imgsize=231765",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "fruits",
        name: "Pineapple",
        price: 40,
        image:
            "https://minnetonkaorchards.com/wp-content/uploads/2021/04/Health-Benefits-of-Pineapple.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "fruits",
        name: "Strawberry",
        price: 180,
        image:
            "https://hips.hearstapps.com/clv.h-cdn.co/assets/15/22/1432664914-strawberry-facts1.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "fruits",
        name: "Guava",
        price: 60,
        image:
            "https://stylesatlife.com/wp-content/uploads/2019/09/Guava-Benefits-Amrood-For-Health-Hair-Skin.jpg.webp",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "fruits",
        name: "Papaya",
        price: 70,
        image: "https://sudhaventures.com/wp-content/uploads/2021/07/Papaya.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "fruits",
        name: "Kiwi",
        price: 160,
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Kiwi_aka.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "fruits",
        name: "Banana",
        price: 30,
        image:
            "https://cdn.mos.cms.futurecdn.net/42E9as7NaTaAi4A6JcuFwG-1200-80.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "fruits",
        name: "Pear",
        price: 50,
        image: "https://images.indianexpress.com/2020/02/pear-fruit_1200.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "fruits",
        name: "Grapes",
        price: 60,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/41P8zMQqR7L._SX466_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "fruits",
        name: "Litchi",
        price: 70,
        image:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvkhr-ln8zGIwI1mY4hwQHxIifLQNBQyWuT-fxzCyNkA713Wq2YxVXWTJSTBCMkmAmLJU&usqp=CAU",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "snacks",
        name: "Lays Green Onion",
        price: 20,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/71lW0CG8P9L._SL1500_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "snacks",
        name: "Haldiram Bhujia",
        price: 60,
        image:
            "https://globalgrocery.in/wp-content/uploads/sites/25/2020/07/Haldiram-bhujia.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "snacks",
        name: "Chings Noodles",
        price: 40,
        image:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSF8cbl4CAJI5PbIVbGhDd9NtkvDp674V4lbDx57gdvh8tldVGlcFNsXseMPDx1DgsbpGk&usqp=CAU",
    },

    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "snacks",
        name: "Marie Gold Biscuits",
        price: 25,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/61ObH8B5QCL._SL1500_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "snacks",
        name: "Haldiram Mixture",
        price: 99,
        image:
            "https://img.dmart.in/images/rwd/products/I/N/a/INamkeens1kgHLD1089XX290216_1_B.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "snacks",
        name: "Choco Chip Cookies",
        price: 30,
        image:
            "https://i.pinimg.com/originals/61/67/d2/6167d2df8b54e89c1789d84e03059f30.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "snacks",
        name: "Maggie",
        price: 12,
        image:
            "https://rukminim1.flixcart.com/image/416/416/ki3gknk0/noodle/z/l/u/840-maggie-masala-noodles-12-instant-noodles-nestle-original-imafxym3qfnvhksa.jpeg?q=70",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "snacks",
        name: "Haldiram Mixture",
        price: 60,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/812y9vywdnL._SL1500_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "snacks",
        name: "Bingo Mad Angles",
        price: 10,
        image:
            "https://d37ky63zmmmzfj.cloudfront.net/production/itemimages/packed_food/snacks_confectionary/snacks/Bingo_Mad%20Angles%20Chilli%20Dhamaka_100%20gm.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "snacks",
        name: "Bingo Mad Angles",
        price: 10,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/814gWY%2BdrSL._SX425_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Coca-Cola",
        price: 20,
        image:
            "https://dodan3whn6dxi.cloudfront.net/wp-content/uploads/2019/04/08144734/COKE-1.25LTR-X-12PC-.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Real Fruit Juice",
        price: 100,
        image:
            "https://res.sastasundar.com/incom/images/product/Real-Fruit-Power-Mixed-Fruit-Juice-1592295355-10009767-1.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Monster Energy Drink",
        price: 99,
        image:
            "https://5.imimg.com/data5/LR/LM/GW/SELLER-59097240/monster-energy-drink-500x500.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Mazaa",
        price: 50,
        image:
            "https://vimanmart.com/pub/media/catalog/product/cache/2b2001d4d1032cbd8c1df97b3ae1c185/p/v/pvm4q00046.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Tropicana",
        price: 101,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/71wMrB2fMBL._SL1500_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Nescafe Coffee",
        price: 35,
        image:
            "https://5.imimg.com/data5/TJ/KA/MY-27719302/nescafe-latte-tin-500x500.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Amul milk",
        price: 22,
        image:
            "https://img.dmart.in/images/rwd/products/I/M/i/IMilk1LAMUL3174xx260521_5_B.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Sprite",
        price: 45,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/61bkEued9fL._SL1500_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Monster Energy Drink",
        price: 99,
        image:
            "https://5.imimg.com/data5/LR/LM/GW/SELLER-59097240/monster-energy-drink-500x500.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Sprite",
        price: 45,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/61bkEued9fL._SL1500_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Soda Water",
        price: 20,
        image:
            "https://4.imimg.com/data4/JL/GQ/MY-27554318/bisleri-600-ml-soda-500x500.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Mirinda",
        price: 55,
        image:
            "https://5.imimg.com/data5/BF/AZ/DG/SELLER-49520187/mirinda-cold-drink-500x500.jpeg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "beverages",
        name: "Amul cool",
        price: 20,
        image:
            "https://5.imimg.com/data5/XR/RS/MY-11935886/amul-kesar-flavored-milk-500x500.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Vim Bar",
        price: 40,
        image:
            "https://rukminim1.flixcart.com/image/416/416/kh9gbrk0/dish-washing-bar/g/d/2/na-1-500-vim-original-imafxbdfcgeqjrbd.jpeg?q=70",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Scroth brite",
        price: 10,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/91%2BRw%2BhgKlS._SL1500_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Vim liquid soap",
        price: 60,
        image:
            "https://5.imimg.com/data5/JW/FG/MY-2548289/vim-liquid-dish-wash-500x500.png",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Surf excel",
        price: 76,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/61rDJVoKpeL._SL1000_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Tide",
        price: 120,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/81czQaYkV8L._SL1500_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Rin bar",
        price: 60,
        image: "https://images-na.ssl-images-amazon.com/images/I/51epMbXlUDL.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Wipes",
        price: 150,
        image: "https://5.imimg.com/data5/NC/LX/MY-1405925/wet-wipes-500x500.png",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Vanish",
        price: 250,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/51fV6rj7k3L._SL1000_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Fabric Softner",
        price: 100,
        image:
            "https://res.cloudinary.com/mtree/image/upload/w_360,q_auto,f_auto,dpr_auto/Downy_US_MW/4w9Xvm5imvycJUaEWLQgYu/746b03496fae01e6cf3f0980cf155c74/Ultra-Downy-April-Fresh_2x.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Light Bulbs",
        price: 599,
        image:
            "https://rukminim1.flixcart.com/image/416/416/kdeum4w0/emergency-light/b/4/r/ssk-emb-07-01-syska-original-imafubkshdtggefy.jpeg?q=70",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Duracell Batteries",
        price: 150,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/71C0bEGPWLL._SL1500_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Garbage bag",
        price: 139,
        image:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBuWcLDyZQnTcyUIZX7VZqSRUfOj7wt9HnRc49ngKDaQP5xbAM8h3aRBBI6Bg&usqp=CAc",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "dailyNeeds",
        name: "Dustbin",
        price: 150,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/610HuYSbRSL._SY355_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "cookingNeeds",
        name: "Ashirvaad Atta",
        price: 115,
        image:
            "https://5.imimg.com/data5/LG/NY/GLADMIN-36776210/aashirvaad-shudh-chakki-whole-wheat-atta-500x500.png",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "cookingNeeds",
        name: "Tata Salt",
        price: 22,
        image:
            "https://www.tatasalt.com/public/front_assets/images/tatasalt_og.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "cookingNeeds",
        name: "Mustard oil",
        price: 130,
        image: "https://images-na.ssl-images-amazon.com/images/I/41YDq-tchUL.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "cookingNeeds",
        name: "Turmeric powder",
        price: 40,
        image:
            "https://b2mart.in/wp-content/uploads/2020/09/47392-Everest-Turmeric-100g.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "cookingNeeds",
        name: "Chilli powder",
        price: 40,
        image:
            "https://www.waangoo.com/content/images/thumbs/0015281_everest-tikhalal-chilli-powder_600.jpeg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "cookingNeeds",
        name: "Basmati Rice",
        price: 450,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/71kCNvUUx5L._SX425_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "cookingNeeds",
        name: "Kissan Ketchup",
        price: 120,
        image:
            "https://www.simpleskincare.com/sk-eu/content/dam/brands/kissan/india/2329670-kissan-fresh-tomato-500.png",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "cookingNeeds",
        name: "Sugar",
        price: 40,
        image:
            "https://rukminim1.flixcart.com/image/416/416/kd94uq80/sugar/y/m/b/5-pure-and-hygenic-sugar-pouch-refined-sugar-madhur-crystal-original-imafu775g3xgbbde.jpeg?q=70",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "cookingNeeds",
        name: "Maida",
        price: 35,
        image:
            "https://5.imimg.com/data5/YY/DF/MY-41746325/premium-maida-500x500.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "cookingNeeds",
        name: "Kissan Jam",
        price: 40,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/6182emaYXFL._SL1000_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "chocolates",
        name: "Dairy Milk",
        price: 40,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/61rOyPund0L._SX522_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "chocolates",
        name: "Perk",
        price: 10,
        image:
            "https://5.imimg.com/data5/VS/EV/KF/SELLER-96565405/perk-chocolate-500x500.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "chocolates",
        name: "Munch",
        price: 20,
        image:
            "https://www.nestle.in/sites/g/files/pydnoa451/files/MUNCH-Rs-5-270x295.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "chocolates",
        name: "Dairy Milk Silk",
        price: 80,
        image:
            "https://rukminim1.flixcart.com/image/416/416/koad9jk0/chocolate/2/4/y/160-dairy-milk-silk-chocolate-1-cadbury-original-imag2s45hasxzhfs.jpeg?q=70",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "chocolates",
        name: "m&m",
        price: 120,
        image: "https://m.media-amazon.com/images/I/818Xz4cHOqL._SX385_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "chocolates",
        name: "KitKat family pack",
        price: 60,
        image: "https://images-na.ssl-images-amazon.com/images/I/41STuvyXQYL.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "chocolates",
        name: "Nutella",
        price: 150,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/41v8vHL%2B5IL.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "chocolates",
        name: "Forero Rocher",
        price: 550,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/713Oz81cyAS._SL1000_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "chocolates",
        name: "Dairy milk Bubbly",
        price: 100,
        image:
            "https://rukminim1.flixcart.com/image/416/416/kkec4280/chocolate/t/p/y/dairy-milk-silk-bubbly-chocolate-bar-120-g-pack-of-3-cadbury-original-imafzregu4hzn67m.jpeg?q=70",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "chocolates",
        name: "Dairy milk Family Pack",
        price: 120,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/61KRD65TtEL._SL1500_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "Pears Soap",
        price: 35,
        image:
            "https://newassets.apollo247.com/pub/media/catalog/product/p/e/pea0039_4.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "Lizol",
        price: 60,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/51E1CAX7bXL._SL1000_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "Lux Shower Gel",
        price: 78,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/51JU-R0bYQL._SY355_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "Harpic",
        price: 55,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/61zl3nbmnBL._SX425_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "Detol Handwash",
        price: 55,
        image:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9rFPeJDhpmnydK-_nuT30MBJVjXb_FsT12veIF-J8y77THlbYu_hsouRImBRAUViegQQ&usqp=CAU",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "Toilet Paper",
        price: 200,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/71m-Gpu0spL._SX679_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "MamaEarth Shampoo",
        price: 350,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/51Akf89dqGL._SL1200_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "MamaEarth Conditioner",
        price: 370,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/61oIHWrj8PL._SL1500_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "Talcum Powder",
        price: 180,
        image:
            "https://chemist2customer.com/images/pictures/cuticura/cuticura_mildly_medicated_body_powder_150g-(gallery).jpg?v=b0a501be",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "Nivea FaceWash",
        price: 115,
        image: "https://m.media-amazon.com/images/I/61LmABL6JKL._SX679_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "Lifebuoy soap",
        price: 20,
        image:
            "https://images-na.ssl-images-amazon.com/images/I/61wnWbAwwFL._SY355_.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "Detol Liquid",
        price: 67,
        image:
            "https://newassets.apollo247.com/pub/media/catalog/product/d/e/det0004.jpg",
    },
    {
        id: Math.floor(Math.random() * 100000),
        count: 0,
        total: 0,
        category: "bathroomNeeds",
        name: "Nivea soap",
        price: 40,
        image:
            "https://res.sastasundar.com/incom/images/product/Nivea-Creme-Care-Soap-Buy-3-Get-1-Free-1604657862-10048273-1.jpg",
    },
]
